### ISSUE TITLE
How is Config Declared

### ISSUE THREAD

**Issue by iFran2019** [mikigal/ConfigAPI#5]
hi, i need the Config class from 

![image](https://github.com/mikigal/ConfigAPI/assets/101476953/1dcf85c2-917c-4c42-af2f-82e7ed215be1)

**Comment by mikigal** [comment]
@iFran2019 
You have to import this class from pl.mikigal.config.Config
If your IDE does not recognize it something is wrong with your Gradle/Maven

**Comment by iFran2019** [comment]
how i can fix this??

**Comment by iFran2019** [comment]
https://github.com/ImperiorDevelopment/Freerank this is my project

**Comment by iFran2019** [comment]
![image](https://github.com/mikigal/ConfigAPI/assets/101476953/40bb23c8-18e3-4af1-8949-0c9d4a8f0cc7)

**Comment by mikigal** [comment]
I don't provide support to 3rd party projects if it's not ConfigAPI's code related.
I guess you added ConfigAPI incorrectly to your Maven - I personally use Gradle so I can't tell anything more.
Looks like it does not put ConfigAPI's classes to your output jar as you get NoClassDefFoundError
