### ISSUE TITLE
Optional config keys

### ISSUE THREAD

**Issue by m7rlin** [mikigal/ConfigAPI#7]
How can I create a value in the config that is optional. That is, at first it does not exist like, for example, the player's "home" location, and later it can be dynamically added to the config?

**Comment by mikigal** [comment]
You have to mark your method with ConfigOptional annotation - then it can simply return null
Then you can change it's value with setter method
I will add information about it to README

**Comment by m7rlin** [comment]
Thank you for fast response.

This works fine for interfaces like 
![image](https://github.com/mikigal/ConfigAPI/assets/11756007/66543da5-9462-4179-925f-7fa07de7702c)

but on serializable classes it won't
![image](https://github.com/mikigal/ConfigAPI/assets/11756007/ce0e18fc-11d0-4d7a-b577-64b72d6af915)

![image](https://github.com/mikigal/ConfigAPI/assets/11756007/3969e4d1-4cc6-4567-b662-d6415f6cc330)

**Comment by mikigal** [comment]
Fixed in #9
