### ISSUE TITLE
Saving config deletes cache

### ISSUE THREAD

**Issue by m7rlin** [mikigal/ConfigAPI#8]
Problem:
If I use the save function then the config is saved but the cache is deleted and the values cannot be read from it.

![image](https://github.com/mikigal/ConfigAPI/assets/11756007/45b0db4b-a06e-4355-b591-0ac7c7480ec4)

![image](https://github.com/mikigal/ConfigAPI/assets/11756007/971f8488-44ec-4c0f-9a69-b1bac0158f00)

![image](https://github.com/mikigal/ConfigAPI/assets/11756007/0e5a5315-b2de-4cf8-8f3d-16861e55d5d6)

Caused by setting the cache to null:
![image](https://github.com/mikigal/ConfigAPI/assets/11756007/ec8493e0-af8d-4326-b3e4-6ff3039f1a92)

Repo: https://github.com/m7rlin/minecraft-plugin-magiczna-kraina/tree/dev/marcin

**Comment by mikigal** [comment]
Please check is it related only to UnvicersalMapSerializer (like in your code) as your variable is HashMap, or in general
Try setting some String, some object which includes Serializable (to test UniversalObjectSerializer) and e. g. Bukkit's Location object and let me about results, as problem may be a bit deeper

**Comment by m7rlin** [comment]
Other types I need to check.

I do not know if this is how it should be used because other versions do not save the configuration.

this works:
![image](https://github.com/mikigal/ConfigAPI/assets/11756007/903ebd8e-eb65-43b0-be5d-65d9013a63fe)

this don't:
![image](https://github.com/mikigal/ConfigAPI/assets/11756007/a85273fe-1b3d-4e9e-959e-790a67084075)

**Comment by mikigal** [comment]
Fixed in https://github.com/mikigal/ConfigAPI/pull/9
